### ISSUE TITLE
question: Does wasm-nn-ggml support streaming response like openai's API

### ISSUE THREAD

**Issue by irhawks** [second-state/llama-utils#15]
### Summary

I have successfully tried to start llama-api-server.wasm application to work. However after I have tried to integrate with openAI compatible applications, I have found the following features:

1. llama-api-server does not support response as a stream, which commonly used with popular LLM applications.
2. Everytime I tried to make a request to llama-api-server, the server always tries to reload layers into GPU(nn-ggml-cuda support), which makes long latency, could this be optimized by loading layers into GPU only at startup?

This two features makes llama-utils less essential for serving llm applications. 
Could these shortages be fixed in the future?

**Comment by hydai** [comment]
Currently, it cannot. The streaming output is just printed to stdout directly when a token is generated. It doesn't return immediately. It must wait until the whole compute function is done to retrieve the output buffer.

However, we are working on extending the WASI-NN spec to make such a feature work; it's still under development and testing; once it's ready, we will update the example program simultaneously. Thanks.
