### ISSUE TITLE
question: easy way to specify a custom prompt?

### ISSUE THREAD

**Issue by rxjx** [second-state/llama-utils#20]
### Summary

I'm trying to use models not in the model list. In some cases the prompt I need doesn't match any of the pre-built prompt templates. I could of course build from source and add code to handle this but it'd be nice to have a way for end-users to be able to specify the prompt as a string, perhaps with option to separate the system prompt as well.

**Comment by juntao** [comment]
You can use the llama-simple program. It takes prompts as you give. So you can use your own template and conversation history.
