### ISSUE TITLE
bug: <|im_end|> appear at the end of resonse

### ISSUE THREAD

**Issue by katopz** [second-state/llama-utils#21]
### Summary

On m3 max I got...

```
[You]: 
Write helloworld code in Rust.

fn main() {
    println!("Hello, world!");
}
<|im_end|>
```

### Reproduction steps

1. `bash <(curl -sSf https://raw.githubusercontent.com/second-state/llama-utils/main/run-llm.sh)`
2. Use `10. OpenHermes-2.5-Mistral-7B`
3. Use `cli`
4. Use `Write helloworld code in Rust.` prompt

### Screenshots

<img width="682" alt="image" src="https://github.com/second-state/llama-utils/assets/97060/c86e6aa5-13e3-47f9-b049-92806ee99d62">

### Any logs you want to share for showing the specific issue

```
Downloading 'llama-chat' wasm ...
######################################################################### 100.0%

starting llama-chat ... 

+ '[' -n '<|im_end|>' ']'
+ '[' -n '' ']'
+ '[' -n '<|im_end|>' ']'
+ wasmedge --dir .:. --nn-preload default:GGML:AUTO:openhermes-2.5-mistral-7b.Q5_K_M.gguf llama-chat.wasm --stream-stdout --prompt-template chatml -r '<|im_end|>' --log-stat
[INFO] Model alias: default
[INFO] Prompt context size: 4096
[INFO] Number of tokens to predict: 1024
[INFO] Number of layers to run on the GPU: 100
[INFO] Batch size for prompt processing: 4096
[INFO] Reverse prompt: <|im_end|>
[INFO] Use default system prompt
[INFO] Prompt template: ChatML
[INFO] Stream stdout: true
[INFO] Log prompts: false
[INFO] Log statistics: true
[INFO] Log all information: false
----------------------------------------------------

[You]: 
Write helloworld code in Rust.

---------------- [LOG: STATISTICS] -----------------

llama_new_context_with_model: n_ctx      = 4096
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_new_context_with_model: kv self size  =  512.00 MB
llama_new_context_with_model: compute buffer total size = 2310.16 MB
llama_new_context_with_model: max tensor size =   102.55 MB
[2023-12-10 23:07:39.379] [info] [WASI-NN] GGML backend: llama_system_info: AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 | 

fn main() {
    println!("Hello, world!");
}
<|im_end|>[2023-12-10 23:07:40.204] [info] [WASI-NN] GGML backend: reverse prompt found

llama_print_timings:        load time =    8383.81 ms
llama_print_timings:      sample time =       0.42 ms /    24 runs   (    0.02 ms per token, 56737.59 tokens per second)
llama_print_timings: prompt eval time =     330.04 ms /    59 tokens (    5.59 ms per token,   178.77 tokens per second)
llama_print_timings:        eval time =     491.95 ms /    24 runs   (   20.50 ms per token,    48.79 tokens per second)
llama_print_timings:       total time =    8878.12 ms

----------------------------------------------------




[You]: 
```

### Model Information

openhermes-2.5-mistral-7b.Q5_K_M.gguf

### Operating system information

macOS 14.1.2 (23B2091)

### ARCH

arm64

### CPU Information

m3 max

### Memory Size

64GB

### GPU Information

metal

### VRAM Size

64GB

**Comment by apepkuss** [comment]
@katopz Thanks for your report. According to the command you use, `--stream-stdout` is used. This option enables the direct output from the plugin without the `post-processing` step. So, if you'd like to get a clear output, then remove `--stream-stdout` from the command.

**Comment by katopz** [comment]
> @katopz Thanks for your report. According to the command you use, `--stream-stdout` is used. This option enables the direct output from the plugin without the `post-processing` step. So, if you'd like to get a clear output, then remove `--stream-stdout` from the command.

I think `--stream-stdout` command is came from `run-llm.sh`?

https://github.com/second-state/llama-utils/blob/main/run-llm.sh#L338-L345

**Comment by alabulei1** [comment]
Hi @katopz 

We have updated the `run-llm.sh` to turn off the streaming output when running models like OpenHermas.

We will release a new version of WasmEdge GGML plugin, which will solve this problem more elegantly.

Please give it a try again and let me know if it works. Thanks.

**Comment by katopz** [comment]
Working now. Thanks! ref 26159695edb5c7a76fb1f41e0bfbe07e4176c0d7
