### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by BGC1** [second-state/llama-utils#4]
wasmedge --dir .:. --nn-preload default:GGML:AUTO:mistral-7b-instruct-v0.1.Q4_K_M.gguf llama-api-server.wasm -m default -p mistral-instruct-v0.1 --stream-stdout
[INFO] Socket address: 0.0.0.0:8080
[INFO] Model alias: default
[INFO] Prompt context size: 4096
[INFO] Number of tokens to predict: 1024
[INFO] Number of layers to run on the GPU: 100
[INFO] Batch size for prompt processing: 4096
[INFO] Prompt template: MistralInstructV01
[INFO] Stream stdout: true
[INFO] Starting server ...
[INFO] Listening on http://0.0.0.0:8080
[CHAT] New chat begins ...
*** [prompt begin] ***
<s>[INST] tell me something [/INST]
*** [prompt end] ***
GGML_ASSERT: /__w/WasmEdge/WasmEdge/plugins/wasi_nn/thirdparty/ggml/llama.cpp:621: data
Aborted (core dumped)

**Comment by juntao** [comment]
Can you tell us more about your system? Mac? Linux? GPU? How much memory? Thanks. 

Can you also confirm the size of the GGUF model file on the disk? Thanks.

**Comment by apepkuss** [comment]
@BGC1 You can run `mistral-7b-instruct-v0.1.Q4_K_M.gguf` with the following command:

```console
wasmedge --dir .:. --nn-preload default:GGML:AUTO:mistral-7b-instruct-v0.1.Q4_K_M.gguf llama-api-server.wasm -p mistral-instruct-v0.1
```
In addition, please check if the model file has been downloaded correctly and completely. As a reference, I provide the size and MD5SUM of the model file on my side:

- Size: 4368438944 (4.37GB)
- MD5SUM: 9cfab7b0e378473415241229dad8de47

By the way, please sync up the code if you git cloned `llama-utils`, as `llama-api-server.wasm` has been updated. Thanks!

**Comment by hydai** [comment]
No more updates. Closing this. If you still have the same issue, feel free to re-open this. Thanks.
