### ISSUE TITLE
question: Running Gorilla OpenFunctions v1?

### ISSUE THREAD

**Issue by ChristianWeyer** [second-state/llama-utils#58]
### Summary

Hey all!

is it possible to run Gorilla OpenFunctions v1 (with function calling support) on WasmEdge?
https://huggingface.co/TheBloke/gorilla-openfunctions-v1-GGUF

Thanks.

**Comment by juntao** [comment]
I think it is certainly possible. We should be able to run all GGUF models. However, this model seems to require a specific prompt template format. Do you want to try it? 

You can use llama-simple to manually assemble and test the raw input. That is to assemble your own text input that confirms to the required template. The commonly used templates are codified in a shared crate for llama-chat and llama-api-server.
