### ISSUE TITLE
got error when trying to run Orca 

### ISSUE THREAD

**Issue by sgt101** [second-state/llama-utils#7]
GGML_ASSERT: /Users/hydai/workspace/WasmEdge/plugins/wasi_nn/thirdparty/ggml/ggml-metal.m:1459 false
Abort trap: 6

Looks like some sort of absolute path in there somewhere but I can't find it...

**Comment by hydai** [comment]
https://github.com/WasmEdge/WasmEdge/blob/master/plugins/wasi_nn/thirdparty/ggml/ggml-metal.m#L1459

If this happens, then it means out of memory. Please provide the hardware information and version you used.

**Comment by sgt101** [comment]
Ahh ok I apologize, I was confused by the message into thinking it was a dependency. 

I am using Master, on a Mac M1 with 16GB so it's not surprising that it can't cope really.
