### ISSUE TITLE
Cant start api-server

### ISSUE THREAD

**Issue by lsch0lz** [second-state/llama-utils#9]
Hi!
I want to start the api-server with an llama2 7b model. When I try to start the server via ```wasmedge --dir .:. --nn-preload default:GGML:AUTO:llama-2-7b-chat.Q5_K_M.gguf llama-api-server.wasm -p llama-2-chat``` I get the following response:
```unknown option: nn-preload```
Any idea why the server doesn't start?

**Comment by juntao** [comment]
Hi, sorry for asking the obvious -- did you have the GGUF file downloaded in your current directory? 

Did you install WasmEdge with the GGML plugin? It is in the install command in the README.

Also try the llama-chat.wasm app in the chat/ folder to see if it works. Thanks.

**Comment by lsch0lz** [comment]
Okay, I didnt installed the GGML Plugin. With the plugin the server starts! Thanks :)
Do you think it would be helpful to add this information to this instruction?
https://github.com/second-state/llama-utils/tree/main/api-server

**Comment by juntao** [comment]
Thanks! Installation is covered here:

https://github.com/second-state/llama-utils/tree/main#requirements

But I agree it is too far removed. Would you mind to send a PR to include a link to the requirements at the top of the api-server README? 😂

**Comment by lsch0lz** [comment]
I added the new link to the README and kept the link to the documentation, so others can find more information about the installation process. Have a look!
